// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerBuild():Promise<string>;

export function PullSecLists():Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function RunDockerContainer():Promise<void>;

export function TestFunction(arg1:string):Promise<any>;
