// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['app']['App']['CloseTerminal'](arg1);
}

export function DockerBuild() {
  return window['go']['app']['App']['DockerBuild']();
}

export function EnsureContainerRunning(arg1) {
  return window['go']['app']['App']['EnsureContainerRunning'](arg1);
}

export function GetCompletion(arg1, arg2) {
  return window['go']['app']['App']['GetCompletion'](arg1, arg2);
}

export function PullSecLists() {
  return window['go']['app']['App']['PullSecLists']();
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function RunDockerContainer() {
  return window['go']['app']['App']['RunDockerContainer']();
}

export function SendInput(arg1, arg2) {
  return window['go']['app']['App']['SendInput'](arg1, arg2);
}

export function StartTerminal(arg1) {
  return window['go']['app']['App']['StartTerminal'](arg1);
}

export function StartTerminalSession(arg1) {
  return window['go']['app']['App']['StartTerminalSession'](arg1);
}

export function TestFunction(arg1) {
  return window['go']['app']['App']['TestFunction'](arg1);
}
