// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerBuild() {
  return window['go']['app']['App']['DockerBuild']();
}

export function PullSecLists() {
  return window['go']['app']['App']['PullSecLists']();
}

export function RunCommand(arg1) {
  return window['go']['app']['App']['RunCommand'](arg1);
}

export function RunDockerContainer() {
  return window['go']['app']['App']['RunDockerContainer']();
}

export function SendInput(arg1) {
  return window['go']['app']['App']['SendInput'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['app']['App']['StartTerminal'](arg1);
}

export function TestFunction(arg1) {
  return window['go']['app']['App']['TestFunction'](arg1);
}
