// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1:number):Promise<void>;

export function DockerBuild():Promise<string>;

export function EnsureContainerRunning(arg1:string):Promise<void>;

export function GetCompletion(arg1:number,arg2:string):Promise<string>;

export function PullSecLists():Promise<void>;

export function RunCommand(arg1:string):Promise<string>;

export function RunDockerContainer():Promise<void>;

export function SendInput(arg1:number,arg2:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StartTerminalSession(arg1:number):Promise<void>;

export function TestFunction(arg1:string):Promise<any>;
